### PR TITLE
Simple health checks for VariedAdStream and ProofOfPlay

### PR DESCRIPTION
**Pull request by hkaya**
Current health checks:
- There must be at least one ad request in past 3 minutes.
- There must be at least one successful ad request in past 15 minutes.
  Getting an ad response back is considered a success.
- There must be at least one PoP request in past 3 minutes.
- There must be at least on successful PoP request in past 15 minutes.
  Both expire and confirm requests count as a success.

### CODE REVIEW

**Comment by natlownes** [comment]
+1

**Comment by hkaya** [comment]
Hey Nat,

Could you please publish the new version to npm when this change is merged? I'm going to need it for app changes. Thank you!

**Comment by markchadwick** [comment]
+1

**Comment by natlownes** [comment]
@hkaya apologies for the wait, this is published @ 1.5.0

**Pull request merged**
